import Head from 'next/head'
import { Inter } from 'next/font/google'
import Dashboard from '@/components/Dashboard'
import { TeamsChart } from '@/components/TeamsChart'
import Image from 'next/image'
import { ProjectDeliveriesChart } from '@/components/ProjectDeliveriesChart'
import Notifications from '@/components/Notifications'
import { CssBaseline, ThemeProvider, Typography, createTheme } from '@mui/material'
import { useState } from 'react'
import { ThemeContext } from '@/contexts/themeContext'
import { getProjectDeliveries, getTeamsStrength } from '@/api'
const statisticCards = [
  {
    title: "Top 10",
    info: "Position in dribbble",
    statistic: "20% Increase from Last Week",
    bgcolor: "#FFF0E6"
  },
  {
    title: "26",
    info: "New employees onboarded",
    statistic: "15% Increase from Last Month",
    bgcolor: "#ECEAFE"
  },
  {
    title: "500",
    info: "New Clients Approached",
    statistic: "5% Increase from Last Week",
    bgcolor: "#E5F7FF"
  },
]
export default function Home({ data, projectsData }) {
  console.log(data.labels);
  console.log(data.data);
  const [mode, setMode] = useState("light")
  const theme = createTheme({
    palette: {
      mode: mode,
    },
  });

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@200;300;400;500;600;700;800&display=swap" rel="stylesheet"></link>
      </Head>
      <ThemeContext.Provider value={{ mode, setMode }}>
        <CssBaseline />
        <ThemeProvider theme={theme}>
          <Dashboard>
            <div style={{ maxHeight: "50%" }} className="row mt-5 ">
              <div className=" col-sm-12 col-md-6 col-lg-4 p-3 ">
                <div >
                  <div className="cardTitle" style={{ color: mode === 'dark' ? '#fff' : "#23262F" }} >

                    Teams Strength
                  </div>
                  <TeamsChart labels={data.labels} numbers={data.data} />
                  <div className="d-flex flex-column  flex-wrap gap-2 align-item-center">
                    <div className="d-flex gap-4">
                      <div className="d-flex w-50 align-items-center gap-2">
                        <div className="marketingIcon">a</div>
                        <div className="chartTitle">Marketing</div>
                      </div>
                      <div className="d-flex w-50 align-items-center gap-2">
                        <div className="developersIcon">b</div>
                        <div className="chartTitle">Developers</div>
                      </div>
                    </div>
                    <div className="d-flex gap-4">
                      <div className="d-flex w-50 align-items-center gap-2">
                        <div className="hrIcon">c</div>
                        <div className="chartTitle">HR</div>
                      </div>
                      <div className="d-flex w-50 align-items-center gap-2">
                        <div className="designIcon">d</div>
                        <div className="chartTitle">Design</div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className=" d-flex flex-column gap-4 col-sm-12 col-md-6 col-lg-4 p-3 ">
                <div className="d-flex justify-content-between align-items-center">
                  <div className="cardTitle" style={{ color: mode === 'dark' ? '#fff' : "#23262F" }}>Employees</div>
                  <div className='d-flex gap-2 align-items-center'>
                    <div className='date'>Aug 25-Sept 25</div>
                    <Image src={require("../assets/icons/arrow-drop-down-line (2) 1.png")} alt="dweew" />
                  </div>
                </div>
                <div className="d-flex justify-content-between">
                  <div className="d-flex justify-content-between flex-column gap-4">
                    <div className="d-flex flex-column gap-2">
                      <div className="d-flex align-items-center employeeItem gap-1">
                        <div className="inactiveBadge"></div>
                        Inactive
                      </div>
                      <div className="quantity">254</div>
                    </div>
                    <div className="d-flex flex-column gap-2">
                      <div className="d-flex align-items-center employeeItem gap-1">
                        <div className="activeBadge"></div>
                        Active
                      </div>
                      <div className="quantity">3000</div>
                    </div>
                    <div className="d-flex flex-column gap-2">
                      <div className="d-flex align-items-center employeeItem gap-1">
                        <div className="totalBadge"></div>
                        Total
                      </div>
                      <div className="quantity">3254</div>
                    </div>
                  </div>
                  <Image src={require("../assets/images/Group 1000000788.png")} alt="dweew" />
                </div>
              </div>
              <div className="d-flex flex-column justify-content-between col-sm-12 gap-2 col-md-6 col-lg-4 p-3 w-full">
                {
                  statisticCards.map((item, index) => (
                    <div key={index} style={{ background: `${item.bgcolor}` }} className="py-2 rounded d-flex flex-column align-items-center gap-2" >
                      <div className="statisticTitle">{item.title}</div>
                      <div className="statisticInfo">{item.info}</div>
                      <div className="statistic">{item.statistic}</div>
                    </div>
                  ))
                }

              </div>
            </div>
            <div style={{ maxHeight: "50%" }} className="row mt-5">
              <div className="col-sm-12  shadow rounded col-md-8 ">
                <div className="d-flex justify-content-between align-items-center">
                  <div className="cardTitle" style={{ color: mode === 'dark' ? '#fff' : "#23262F" }}>Project Deliveries</div>
                  <div className="d-flex gap-3 align-items-center">
                    <div className="d-flex align-items-center gap-1" style={{ color: mode === 'dark' ? '#fff' : "#000" }}>
                      <div className="inactiveBadge"></div>
                      Achieved
                    </div>
                    <div className="d-flex align-items-center gap-1" style={{ color: mode === 'dark' ? '#fff' : "#000" }}>
                      <div className="activeBadge"></div>
                      Target
                    </div>
                  </div>
                </div>
                <ProjectDeliveriesChart labels={projectsData.labels} numbers1={projectsData.data1} numbers2={projectsData.data2} />
              </div>
              <div className="col-sm-12 col-md-4">
                <Notifications />
              </div>
            </div>
          </Dashboard>
        </ThemeProvider>
      </ThemeContext.Provider >
    </>
  )
}
export async function getStaticProps() {
  const res1 = await getTeamsStrength()
  const res2 = await getProjectDeliveries()
  return {
    props: {
      data: res1,
      projectsData: res2
    }
  }
}